spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/moda
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false # 스레드풀 트랜잭션 직후 스레드 반납

  devtools:
    livereload:
      enabled: true # 자동 재시작, LiveReload, 캐시 무효화

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace # 실제 파라미터 바인딩 값까지 다 볼 수 있어서 JPA 디버깅에 매우 유용